# SPDX-FileCopyrightText: 2017-now Alex Turbov <zaufi@pm.me>
# SPDX-License-Identifier: CC0-1.0
- id: reveal-unused-pattern-files
  name: Check for unused expectation files
  description: Check for expectation files that are not used by tests.
  entry: pytest --pm-reveal-unused-files --pm-fail-on-unused-files
  language: python
  pass_filenames: false
  stages: [manual]
