# SPDX-FileCopyrightText: 2024-now, Alex Turbov <zaufi@pm.me>
# SPDX-License-Identifier: CC0-1.0

name: CI Testing

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    name: Hatch build and run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          hatch env create

      - name: Build a package
        run: |
          hatch build

      - name: Run tests
        run: |
          hatch run test

      - name: Run linters
        run: |
          hatch run all
